<?php
/** Front page. @package Formlooq_Theme */
$c = formlooq_content();
$h = $c['home'];
get_header();
?>
<main id="main">
	<section class="hero"><div class="looq-container hero-grid"><div><span class="eyebrow"><?php echo esc_html( $h['eyebrow'] ); ?></span><h1><?php echo wp_kses_post( str_replace( 'CSS', '<span class="accent">CSS</span>', $h['title'] ) ); ?></h1><p class="hero-lead"><?php echo esc_html( $h['lead'] ); ?></p><div class="hero-actions"><a class="button button-primary" href="<?php echo esc_url( formlooq_download_url() ); ?>"><?php echo esc_html( $c['actions']['download'] ); ?></a><a class="button button-secondary" href="<?php echo esc_url( formlooq_url( 'docs' ) ); ?>"><?php echo esc_html( $c['actions']['docs'] ); ?></a></div><div class="hero-meta"><span>WordPress 6.5+</span><span>PHP 8.1+</span><span>GPLv2+</span></div></div>
	<div class="builder-window" aria-label="<?php echo esc_attr( formlooq_is_fa() ? 'پیش‌نمایش فرم‌ساز' : 'Form builder preview' ); ?>"><div class="window-bar"><div class="window-dots"><i></i><i></i><i></i></div><span>Form LOOQ Builder</span></div><div class="builder-canvas"><aside class="builder-sidebar"><img class="builder-logo" src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/logo-mark.svg' ); ?>" alt=""><div class="builder-tool">Text</div><div class="builder-tool">Email</div><div class="builder-tool">Phone</div><div class="builder-tool">Select</div><div class="builder-tool">Rating</div></aside><div class="form-preview"><div class="form-card"><h3><?php echo esc_html( formlooq_is_fa() ? 'فرم درخواست پروژه' : 'Project inquiry' ); ?></h3><p><?php echo esc_html( formlooq_is_fa() ? 'کمی درباره نیازتان بنویسید.' : 'Tell us a little about your needs.' ); ?></p><span class="mock-label"><?php echo esc_html( formlooq_is_fa() ? 'نام و نام خانوادگی' : 'Full name' ); ?></span><div class="mock-input"></div><span class="mock-label"><?php echo esc_html( formlooq_is_fa() ? 'ایمیل' : 'Email address' ); ?></span><div class="mock-input"></div><span class="mock-label"><?php echo esc_html( formlooq_is_fa() ? 'توضیحات' : 'Message' ); ?></span><div class="mock-input"></div><div class="mock-submit"><?php echo esc_html( formlooq_is_fa() ? 'ارسال درخواست' : 'Send inquiry' ); ?></div></div></div></div></div></div></section>
	<section class="trust-strip"><div class="looq-container trust-grid"><?php foreach ( $h['stats'] as $stat ) : ?><div class="trust-item"><strong class="trust-number"><?php echo esc_html( $stat[0] ); ?></strong><span class="trust-label"><?php echo esc_html( $stat[1] ); ?></span></div><?php endforeach; ?></div></section>
	<section class="section"><div class="looq-container"><div class="section-head"><h2><?php echo esc_html( $h['features_title'] ); ?></h2><p><?php echo esc_html( $h['features_lead'] ); ?></p></div><div class="feature-grid"><?php foreach ( $h['features'] as $i => $feature ) : ?><article class="feature-card"><span class="feature-index"><?php echo esc_html( sprintf( '%02d', $i + 1 ) ); ?></span><h3><?php echo esc_html( $feature[0] ); ?></h3><p><?php echo esc_html( $feature[1] ); ?></p></article><?php endforeach; ?></div></div></section>
	<section class="section section-muted"><div class="looq-container split"><div class="split-copy"><span class="eyebrow">Local-first data</span><h2><?php echo esc_html( $h['local_title'] ); ?></h2><p><?php echo esc_html( $h['local_text'] ); ?></p><ul class="check-list"><?php foreach ( $h['local_points'] as $point ) : ?><li><?php echo esc_html( $point ); ?></li><?php endforeach; ?></ul></div><div class="code-window"><div class="code-window-head"><span>WordPress</span><span>shortcode</span></div><pre><code>[looq_form id="12"]

dir="auto"
button="Send inquiry"
sent="Thanks — we got it."</code></pre></div></div></section>
	<section class="section"><div class="looq-container"><div class="section-head"><h2><?php echo esc_html( $h['use_title'] ); ?></h2><p><?php echo esc_html( $h['use_lead'] ); ?></p></div><div class="use-grid"><?php foreach ( $h['use_cases'] as $item ) : ?><article class="use-card"><span class="use-icon"><?php echo esc_html( $item[0] ); ?></span><h3><?php echo esc_html( $item[1] ); ?></h3><p><?php echo esc_html( $item[2] ); ?></p></article><?php endforeach; ?></div></div></section>
	<section class="section section-muted support-section"><div class="looq-container support-grid"><div class="support-copy"><span class="eyebrow"><?php echo esc_html( formlooq_is_fa() ? 'ساخته‌شده با بازخورد واقعی' : 'Built with real feedback' ); ?></span><h2><?php echo esc_html( formlooq_is_fa() ? 'مشکلی پیدا کردید یا ایده‌ای دارید؟' : 'Found a bug or have a better idea?' ); ?></h2><p><?php echo esc_html( formlooq_is_fa() ? 'جزئیات را برای ما بفرستید. گزارش‌های دقیق به ما کمک می‌کنند مشکل را سریع‌تر بازتولید کنیم و قابلیت‌های بعدی را بر اساس نیاز واقعی کاربران اولویت‌بندی کنیم.' : 'Send us the details. Clear reports help us reproduce problems faster and prioritize what the community genuinely needs next.' ); ?></p><div class="support-options"><div class="support-option"><strong><?php echo esc_html( formlooq_is_fa() ? 'گزارش باگ' : 'Report a bug' ); ?></strong><span><?php echo esc_html( formlooq_is_fa() ? 'مراحل تکرار، نتیجه فعلی و نتیجه مورد انتظار را بنویسید.' : 'Include reproduction steps, the current result, and what you expected.' ); ?></span></div><div class="support-option"><strong><?php echo esc_html( formlooq_is_fa() ? 'درخواست قابلیت' : 'Request a feature' ); ?></strong><span><?php echo esc_html( formlooq_is_fa() ? 'مسئله‌ای را که می‌خواهید حل کنید توضیح دهید، نه فقط نام قابلیت را.' : 'Describe the problem you need to solve, not only the feature name.' ); ?></span></div></div></div><div class="support-form"><h2><?php echo esc_html( formlooq_is_fa() ? 'ارسال بازخورد' : 'Send feedback' ); ?></h2><?php echo formlooq_support_form(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Form LOOQ renders and escapes its own form markup. ?></div></div></section>
	<section class="cta"><div class="looq-container"><div class="cta-box"><h2><?php echo esc_html( $h['cta_title'] ); ?></h2><p><?php echo esc_html( $h['cta_text'] ); ?></p><a class="button" href="<?php echo esc_url( formlooq_download_url() ); ?>"><?php echo esc_html( $c['actions']['download'] ); ?></a></div></div></section>
</main>
<?php get_footer(); ?>
